export default {
  DATABASE_URL: 'DATABASE_URL',
  JWT_SECRET: 'JWT_SECRET',
  REDIS: {
    URL: 'REDIS_URL',
    PASSWORD: 'REDIS_PASSWORD',
    PORT: 'REDIS_PORT',
    HOST: 'REDIS_HOST',
  },
  MAILTRAP: {
    SENDER_EMAIL: 'MAIL_SENDER_EMAIL',
    HOSTNAME: 'MAIL_HOSTNAME',
    PORT: 'MAIL_PORT',
    AUTH_USER: 'MAIL_AUTH_USER',
    AUTH_PASS: 'MAIL_AUTH_PASS',
  },
};
