export default {
  DATABASE_URL: 'DATABASE_URL',
  JWT_SECRET: 'JWT_SECRET',
  REDIS: {
    URL: 'REDIS_URL',
    PASSWORD: 'REDIS_PASSWORD',
    PORT: 'REDIS_PORT',
    HOST: 'REDIS_HOST',
  },
  MAILGUN: {
    SENDER_EMAIL: 'MAIL_SENDER_EMAIL',
    HOSTNAME: 'MAIL_HOSTNAME',
    PORT: 'MAIL_PORT',
    AUTH_USER: 'MAIL_AUTH_USER',
    AUTH_PASS: 'MAIL_AUTH_PASS',
    EMAIL_SECURE: 'EMAIL_SECURE',
  },
  GCP: {
    PROJECT_ID: 'GCP_PROJECT_ID',
    CLIENT_EMAIL: 'GCP_CLIENT_EMAIL',
    BUCKET_NAME: 'GCP_BUCKET_NAME',
    PRIVATE_KEY: 'GCP_PRIVATE_KEY',
  },
  JOBS: {
    OVERDUE_THRESHOLD_DAYS: 'JOBS_OVERDUE_THRESHOLD_DAYS',
    SESSION_EXPIRY_DAYS: 'JOBS_SESSION_EXPIRY_DAYS',
    CREDIT_REVIEW_THRESHOLD_DAYS: 'JOBS_CREDIT_REVIEW_THRESHOLD_DAYS',
  },
};
